version: '3.2'

services:

  php:
    restart: "no"
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/console-animals-app
      - ./php/configs.ini:/usr/local/etc/php/conf.d/configs.ini
